services:
  sifpi-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sifpi-fe
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NODE_ENV: production
    restart: unless-stopped
