name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-production:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
        run: railway up --service=${{ secrets.SVC_ID }} --environment=production

  deploy-staging:
    if: ${{ github.ref == 'refs/heads/staging' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to staging
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_STAGING }}
        run: railway up --service=${{ secrets.SVC_ID }} --environment=staging
